package com.mioacademy.app.discover

import com.mioacademy.app.core.CareerPath
import com.mioacademy.app.core.ExamType

/**
 * Auto-generated bachelor dataset from BACHELOR LISTt.xlsx (seed data).
 * Year-to-year fields (dates, fees, quotas) are guidance only — always
 * paired with the official-notice caveat in the UI. Do not treat as final.
 */
object BachelorDataset {
    val programs: List<BachelorProgram> = listOf(
        BachelorProgram(
            id = "bologna__international_relations_and_diplomatic_affairs", universityId = "bologna", universityName = "Bologna",
            city = "Bologna", region = "Emilia-Romagna",
            programName = "International Relations and Diplomatic Affairs", fieldCategory = FieldCategory.LAW_INTERNATIONAL,
            relatedCareers = listOf(CareerPath.LAW), primaryStudyArea = ExamType.TOLC_SU,
            admissionExam = "Güncel resmi duyuru kontrol edilmeli", admissionRoute = "",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf(), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "bologna__economics_and_finance", universityId = "bologna", universityName = "Bologna",
            city = "Bologna", region = "Emilia-Romagna",
            programName = "Economics and Finance", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "SAT", admissionRoute = "SAT",
            languageRequirement = "IELTS (min. 6.0)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("SAT"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "bologna__building_constructions_engineering", universityId = "bologna", universityName = "Bologna",
            city = "Ravenna", region = "Emilia-Romagna",
            programName = "Building Constructions Engineering", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "10.03.2025",
            deadlineNote = "06.05.2025 / 14.07.2025",
            admissionNotes = "NON-EU KONTENJAN: 110 IELTS ve TOLC’u başvuru sırasında ister. TOLC-I skorlarını okul CISIA’dan kendisi çekecek. Bundan dolayı UNIBO ve CISIA kaydı yapılırken kişisel bilgiler ve maillerin birebir aynı olmalı. SON TOLC-I’ı baz alır. Öğrenci TOLC-I math bölümünden 5/20’den düşük puan alırsa değerlendirmeye alınmaz. RANKING: 22.05.2025 Kazandıktan sonra hemen kayıt yapılmasını ister. 13/20den düşük alıp kabul edilirse de okula başladığında ofa(mat ile ilgili ek derslere tabi olacaktır).  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "bologna__statistical_science", universityId = "bologna", universityName = "Bologna",
            city = "Bologna", region = "Emilia-Romagna",
            programName = "Statistical Science", fieldCategory = FieldCategory.SCIENCE_BIOTECH,
            relatedCareers = listOf(CareerPath.BIOLOGY), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "bologna__european_studies", universityId = "bologna", universityName = "Bologna",
            city = "Bologna", region = "Emilia-Romagna",
            programName = "European Studies", fieldCategory = FieldCategory.OTHER,
            relatedCareers = listOf(CareerPath.OTHER), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Geçen yıl Şubat",
            deadlineNote = "Geçen yıl Mayıs",
            admissionNotes = "İlk yılı Belçika'da olduğu için süreci farklı ilerliyor.  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "bologna__genomics", universityId = "bologna", universityName = "Bologna",
            city = "Bologna", region = "Emilia-Romagna",
            programName = "Genomics", fieldCategory = FieldCategory.SCIENCE_BIOTECH,
            relatedCareers = listOf(CareerPath.BIOLOGY), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "05.03.2025",
            deadlineNote = "05.05.2025",
            admissionNotes = "NON-EU KONTENJAN: 12 IELTS’i başvuru sırasında ister.  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "bologna__international_studies", universityId = "bologna", universityName = "Bologna",
            city = "Forlì", region = "Emilia-Romagna",
            programName = "International Studies", fieldCategory = FieldCategory.OTHER,
            relatedCareers = listOf(CareerPath.OTHER), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Güncel resmi duyuru kontrol edilmeli", admissionRoute = "",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf(), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "bologna__management_and_economics", universityId = "bologna", universityName = "Bologna",
            city = "Forlì", region = "Emilia-Romagna",
            programName = "Management and Economics", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "SAT", admissionRoute = "SAT",
            languageRequirement = "IELTS (min. 6.0)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Geçen yıl Mayıs",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("SAT"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "bologna__economics_of_tourism_and_cities", universityId = "bologna", universityName = "Bologna",
            city = "Rimini", region = "Emilia-Romagna",
            programName = "Economics of Tourism and Cities", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "SAT", admissionRoute = "SAT",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("SAT"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "bologna__economics_politics_and_social_sciences", universityId = "bologna", universityName = "Bologna",
            city = "Rimini", region = "Emilia-Romagna",
            programName = "Economics, Politics and Social Sciences", fieldCategory = FieldCategory.LAW_INTERNATIONAL,
            relatedCareers = listOf(CareerPath.LAW), primaryStudyArea = ExamType.TOLC_SU,
            admissionExam = "SAT", admissionRoute = "SAT",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("SAT"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "bologna__pharmacy", universityId = "bologna", universityName = "Bologna",
            city = "Rimini", region = "Emilia-Romagna",
            programName = "Pharmacy", fieldCategory = FieldCategory.SCIENCE_BIOTECH,
            relatedCareers = listOf(CareerPath.BIOLOGY), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-F",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "single cycle: 5 years NON-EU KONTENJAN: 35 / 5 Son TOLC geçerli  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-F olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "cafoscari__digital_management", universityId = "cafoscari", universityName = "Ca'Foscari",
            city = "Treviso", region = "Veneto",
            programName = "Digital Management", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Güncel resmi duyuru kontrol edilmeli", admissionRoute = "",
            languageRequirement = "IELTS-TOEFL (5.5-72 min.)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "12.03.2025 / 28.02.2025 / 19.12.2024",
            deadlineNote = "03.04.2025",
            admissionNotes = "€8,740 per year",
            extraNotes = "08.08.2025 | Digital project manager  Digital manager  Business developer  Growth hacker",
            tags = listOf(), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "cafoscari__business_administration_business_administration_and_management", universityId = "cafoscari", universityName = "Ca'Foscari",
            city = "Venezia", region = "Veneto",
            programName = "Business Administration - Business Administration and Management", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E",
            languageRequirement = "IELTS (min. 6.0)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "12.03.2025 / 28.02.2025 / 19.12.2024",
            deadlineNote = "03.04.2025",
            admissionNotes = "Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E olarak geçiyordu).",
            extraNotes = "08.08.2025 | Management and supervision in the private sector  Human resource management  Workplace organisation  Marketing  Accountancy  Finance  Sales and distribution",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "cafoscari__economics_and_business_economics_markets_and_finance_curriculum", universityId = "cafoscari", universityName = "Ca'Foscari",
            city = "Venezia", region = "Veneto",
            programName = "Economics and Business - Economics, Markets and Finance Curriculum", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E",
            languageRequirement = "IELTS-TOEFL (5.5-72 min.)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "12.03.2025 / 28.02.2025 / 19.12.2024",
            deadlineNote = "03.04.2025",
            admissionNotes = "Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E olarak geçiyordu).",
            extraNotes = "08.08.2025 | Accounting  Financial and Administrative Management  Banking  Advertising",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "cafoscari__philosophy_international_and_economic_studies", universityId = "cafoscari", universityName = "Ca'Foscari",
            city = "Venezia", region = "Veneto",
            programName = "Philosophy, International and Economic Studies", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E - Entry Test",
            languageRequirement = "IELTS-TOEFL (5.5-72 min.)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "12.03.2025 / 28.02.2025 / 19.12.2024",
            deadlineNote = "03.04.2025",
            admissionNotes = "Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E - Entry Test olarak geçiyordu).",
            extraNotes = "08.08.2025",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "cafoscari__computer_science_data_science", universityId = "cafoscari", universityName = "Ca'Foscari",
            city = "Venezia", region = "Veneto",
            programName = "Computer Science - Data Science", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "12.03.2025 / 28.02.2025 / 19.12.2024",
            deadlineNote = "03.04.2025",
            admissionNotes = "Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I olarak geçiyordu).",
            extraNotes = "08.08.2025",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "cafoscari__hospitality_innovation_and_e_tourism", universityId = "cafoscari", universityName = "Ca'Foscari",
            city = "Venezia", region = "Veneto",
            programName = "Hospitality Innovation and e-Tourism", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E / SAT",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "12.03.2025 / 28.02.2025 / 19.12.2024",
            deadlineNote = "03.04.2025",
            admissionNotes = "Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E / SAT olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S", "SAT (alternatif)"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "cagliari__business_and_economics", universityId = "cagliari", universityName = "Cagliari",
            city = "Cagliari", region = "Sardegna",
            programName = "Business and Economics", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "camerino__biosciences_and_biotechnology", universityId = "camerino", universityName = "Camerino",
            city = "Camerino", region = "Marche",
            programName = "Biosciences and Biotechnology", fieldCategory = FieldCategory.SCIENCE_BIOTECH,
            relatedCareers = listOf(CareerPath.BIOLOGY), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "/", admissionRoute = "/",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "31.03.2025",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf(), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "marche__digital_economics_and_business", universityId = "marche", universityName = "Marche",
            city = "Ancona", region = "Marche",
            programName = "Digital Economics and Business", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Belge Değerlendirme", admissionRoute = "Document Evaluation",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "01.03.2025",
            deadlineNote = "01.03.2025",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Belge Değerlendirme"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "messina__political_sciences_and_international_relations", universityId = "messina", universityName = "Messina",
            city = "Messina", region = "Sicilia",
            programName = "Political Sciences and International Relations", fieldCategory = FieldCategory.LAW_INTERNATIONAL,
            relatedCareers = listOf(CareerPath.LAW), primaryStudyArea = ExamType.TOLC_SU,
            admissionExam = "Belge Değerlendirme", admissionRoute = "Document Evaluation",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "01.02.2025",
            deadlineNote = "21.02.2025",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Belge Değerlendirme"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "messina__business_management", universityId = "messina", universityName = "Messina",
            city = "Messina", region = "Sicilia",
            programName = "Business Management", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Belge Değerlendirme", admissionRoute = "Document Evaluation",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "28.03.2025 / 30.05.2025",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Belge Değerlendirme"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "messina__transnational_and_european_legal_studies", universityId = "messina", universityName = "Messina",
            city = "Messina", region = "Sicilia",
            programName = "Transnational and European Legal Studies", fieldCategory = FieldCategory.LAW_INTERNATIONAL,
            relatedCareers = listOf(CareerPath.LAW), primaryStudyArea = ExamType.TOLC_SU,
            admissionExam = "Belge Değerlendirme", admissionRoute = "Document Evaluation",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "28.03.2025 / 30.05.2025",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Belge Değerlendirme"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "messina__marine_biology_and_blue_biotechnologies", universityId = "messina", universityName = "Messina",
            city = "Messina", region = "Sicilia",
            programName = "Marine Biology and Blue Biotechnologies", fieldCategory = FieldCategory.SCIENCE_BIOTECH,
            relatedCareers = listOf(CareerPath.BIOLOGY), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Belge Değerlendirme", admissionRoute = "Document Evaluation",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "28.03.2025 / 30.05.2025",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Belge Değerlendirme"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "messina__data_analysis", universityId = "messina", universityName = "Messina",
            city = "Messina", region = "Sicilia",
            programName = "Data Analysis", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "Belge Değerlendirme", admissionRoute = "Document Evaluation",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "28.03.2025 / 30.05.2025",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Belge Değerlendirme"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "messina__civil_engineering", universityId = "messina", universityName = "Messina",
            city = "Messina", region = "Sicilia",
            programName = "Civil Engineering", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "Belge Değerlendirme", admissionRoute = "Document Evaluation",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "28.03.2025 / 30.05.2025",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Belge Değerlendirme"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "messina__computer_science", universityId = "messina", universityName = "Messina",
            city = "Messina", region = "Sicilia",
            programName = "Computer Science", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "Belge Değerlendirme", admissionRoute = "Document Evaluation",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "28.03.2025 / 30.05.2025",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Belge Değerlendirme"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "milano__international_politics_law_and_economics", universityId = "milano", universityName = "Milano",
            city = "Milano", region = "Lombardia",
            programName = "International Politics, Law and Economics", fieldCategory = FieldCategory.LAW_INTERNATIONAL,
            relatedCareers = listOf(CareerPath.LAW), primaryStudyArea = ExamType.TOLC_SU,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "13.03.2025",
            deadlineNote = "29.05.2025",
            admissionNotes = "Non-eu kontenjan:25 Değerlendirilmeye alınabilmek için her ders alanında soruların min. %50'sini doğru cevaplanmış olmalıdır. En yüksek TOLC skorunu baz alır.  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E olarak geçiyordu).",
            extraNotes = "EU kontenjan: 25  -TOLC-E sınavında; her bir ders alanında olumlu C28olarak değerlendirilebilmek için adayların soruların en az %50'sini doğru cevaplamaları gerekir.",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "milano__economics_behavior_data_and_policy", universityId = "milano", universityName = "Milano",
            city = "Milano", region = "Lombardia",
            programName = "Economics, Behavior, Data and Policy", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "13.03.2025",
            deadlineNote = "29.05.2025",
            admissionNotes = "non-eu kontenjan:15 eu kontenjan:100 TOLC-E'de math ve logic kısmına öncelik verilir. Matematik ve mantık bölümlerinde genel olarak 10 puan alamayan  öğrenci diskalife edilecektir. En yüksek TOLC skorunu baz alır.  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E olarak geçiyordu).",
            extraNotes = "100+15 TOLC-E'de math ve logic kısmına öncelik verilir.",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "milano_bicocca__economics_and_science_for_environmental_sustainability", universityId = "milano_bicocca", universityName = "MILANO-BICOCCA",
            city = "Milano", region = "Lombardia",
            programName = "Economics and Science for Environmental Sustainability", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "07.03.2025",
            admissionNotes = "BU YIL AÇILAN BİR BÖLÜM  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "milano_bicocca__physical_sciences_for_innovative_technologies", universityId = "milano_bicocca", universityName = "MILANO-BICOCCA",
            city = "Milano", region = "Lombardia",
            programName = "Physical Sciences for Innovative Technologies", fieldCategory = FieldCategory.SCIENCE_BIOTECH,
            relatedCareers = listOf(CareerPath.BIOLOGY), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "07.03.2025",
            admissionNotes = "BU YIL AÇILAN BİR BÖLÜM  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "napoli__international_business_administration_and_management", universityId = "napoli", universityName = "Napoli",
            city = "Napoli", region = "Campania",
            programName = "International Business Administration and Management", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Güncel resmi duyuru kontrol edilmeli", admissionRoute = "",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf(), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "napoli__business_administration", universityId = "napoli", universityName = "Napoli",
            city = "Napoli", region = "Campania",
            programName = "Business Administration", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Güncel resmi duyuru kontrol edilmeli", admissionRoute = "",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf(), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "padova__animal_care", universityId = "padova", universityName = "Padova",
            city = "Padova", region = "Veneto",
            programName = "Animal Care", fieldCategory = FieldCategory.SCIENCE_BIOTECH,
            relatedCareers = listOf(CareerPath.BIOLOGY), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-F - Interview",
            languageRequirement = "IELTS (min. 6.0)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "07.03.2025",
            admissionNotes = "Başvuranların Matematik, Fizik, Biyoloji, Kimya, Analitik ve Mantık becerilerine iyi hakim olması gerekir TOLC sonuçları, 1 Ocak 2023'ten 7 Mart 2025'e kadar AB dışı öğrenciler için alınan testler için geçerlidir.  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-F - Interview olarak geçiyordu).",
            extraNotes = "TOLC results are valid fort tests taken – From 1 January 2023 to 7 March 2025 for NON-EU students | Graduates work in private and public organisations where management, health, welfare and preservation of animals are driven by a modern and international approach. Job opportunities include taking care of animals in a controlled environment and assisting experts in the monitoring of animals intended…",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "padova__biology_of_human_and_environmental_health", universityId = "padova", universityName = "Padova",
            city = "Padova", region = "Veneto",
            programName = "Biology of Human and Environmental Health", fieldCategory = FieldCategory.HEALTH_SCIENCES,
            relatedCareers = listOf(CareerPath.PHARMACY), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I",
            languageRequirement = "IELTS (min. 6.0)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "non-eu kontenjan:25 Seçim sürecine katılım için geçerli olması için İngilizce TOLC-I sınavının a) 1 Ocak 2024 ile 14 Mart 2025 tarihleri ​​arasında alınmış olması ve 17 Mart 2025 tarihine kadar uygulama platformunun ilgili yerine yüklenmiş olması; b) 18/50'den büyük veya eşit bir asgari puana sahip olması  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I olarak geçiyordu).",
            extraNotes = "NON-EU 25 kontenjan",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "padova__earth_and_climate_dynamics", universityId = "padova", universityName = "Padova",
            city = "Padova", region = "Veneto",
            programName = "Earth and Climate Dynamics", fieldCategory = FieldCategory.SCIENCE_BIOTECH,
            relatedCareers = listOf(CareerPath.BIOLOGY), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I",
            languageRequirement = "IELTS (min. 6.0)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "02.02.2025 23.59",
            admissionNotes = "Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I olarak geçiyordu).",
            extraNotes = "01.10.2025",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "padova__information_engineering", universityId = "padova", universityName = "Padova",
            city = "Padova", region = "Veneto",
            programName = "Information Engineering", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I",
            languageRequirement = "IELTS (min. 6.0)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "07.03.2025",
            admissionNotes = "TOLC-I sonuçları başvuru çağrısının son tarihinden sonra yüklenebilir. Seçim sürecine katılım için geçerli olması için İngilizce TOLC-I sınavının a) 1 Ocak 2024 ile 14 Mart 2025 tarihleri ​​arasında alınmış olması ve 17 Mart 2025 tarihine kadar başvuruya yüklenmiş olması gerekir b) 24/50'den büyük veya eşit bir asgari puana sahip olması gerekir  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "padova__psychological_science", universityId = "padova", universityName = "Padova",
            city = "Padova", region = "Veneto",
            programName = "Psychological Science", fieldCategory = FieldCategory.PSYCHOLOGY_SOCIAL,
            relatedCareers = listOf(CareerPath.PSYCHOLOGY), primaryStudyArea = ExamType.TOLC_PSI,
            admissionExam = "Üniversite Sınavı", admissionRoute = "UNIVERSITY EXAM (26.03.2025)",
            languageRequirement = "IELTS (min. 6.0)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "07.03.2025",
            admissionNotes = "Non-Eu 45 kontenjan",
            extraNotes = "",
            tags = listOf("Üniversite Sınavı"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "padova__techniques_and_methods_in_psychological_science", universityId = "padova", universityName = "Padova",
            city = "Padova", region = "Veneto",
            programName = "Techniques and Methods in Psychological Science", fieldCategory = FieldCategory.PSYCHOLOGY_SOCIAL,
            relatedCareers = listOf(CareerPath.PSYCHOLOGY), primaryStudyArea = ExamType.TOLC_PSI,
            admissionExam = "Üniversite Sınavı", admissionRoute = "UNIVERSITY EXAM (26.03.2025)",
            languageRequirement = "IELTS (min. 6.0)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "07.03.2025",
            admissionNotes = "ONLINE BİR BÖLÜM",
            extraNotes = "",
            tags = listOf("Üniversite Sınavı"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "pavia__artificial_intelligence", universityId = "pavia", universityName = "Pavia",
            city = "Pavia", region = "Lombardia",
            programName = "Artificial Intelligence", fieldCategory = FieldCategory.HUMANITIES,
            relatedCareers = listOf(CareerPath.OTHER), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "pavia__social_sciences_for_global_challenges", universityId = "pavia", universityName = "Pavia",
            city = "Pavia", region = "Lombardia",
            programName = "Social Sciences for Global Challenges", fieldCategory = FieldCategory.SCIENCE_BIOTECH,
            relatedCareers = listOf(CareerPath.BIOLOGY), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Belge Değerlendirme", admissionRoute = "Document Evaluation",
            languageRequirement = "IELTS (min. 6.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "18.03.2025 (3.round)",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Belge Değerlendirme"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "perugia__engineering_management", universityId = "perugia", universityName = "Perugia",
            city = "Perugia", region = "Umbria",
            programName = "Engineering Management", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "/", admissionRoute = "/",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf(), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "politecnico_di_milano__interaction_design", universityId = "politecnico_di_milano", universityName = "Politecnico di Milano",
            city = "Milano", region = "Lombardia",
            programName = "Interaction Design", fieldCategory = FieldCategory.ARCHITECTURE_DESIGN,
            relatedCareers = listOf(CareerPath.ARCHITECTURE, CareerPath.DESIGN), primaryStudyArea = ExamType.TIL_A,
            admissionExam = "Üniversite Sınavı", admissionRoute = "University Exam (03.08.2025) In Italy",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "31.05.2025",
            admissionNotes = "Uluslararasi ogrenciler 31 Mayis 2025'e kadar TOLD sinavina kayit yaptirmali.  Sınav İtalya'da 3 eylül 2025 tarihinde üniversitedeki bilgisayarlar üzerinden yapılacaktır.",
            extraNotes = "",
            tags = listOf("Üniversite Sınavı"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "politecnico_di_torino__civil_and_envirnmental_engineering", universityId = "politecnico_di_torino", universityName = "Politecnico di Torino",
            city = "Torino", region = "Piemonte",
            programName = "Civil and Envirnmental Engineering", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "TIL-I", admissionRoute = "TIL-I",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("TIL-I"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "politecnico_di_torino__electronic_and_communications_engineering", universityId = "politecnico_di_torino", universityName = "Politecnico di Torino",
            city = "Torino", region = "Piemonte",
            programName = "Electronic and Communications Engineering", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "TIL-I", admissionRoute = "TIL-I",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("TIL-I"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "politecnico_di_torino__automative_engineering", universityId = "politecnico_di_torino", universityName = "Politecnico di Torino",
            city = "Torino", region = "Piemonte",
            programName = "Automative Engineering", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "TIL-I", admissionRoute = "TIL-I",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("TIL-I"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "politecnico_di_torino__computer_engineering", universityId = "politecnico_di_torino", universityName = "Politecnico di Torino",
            city = "Torino", region = "Piemonte",
            programName = "Computer Engineering", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "TIL-I", admissionRoute = "TIL-I",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("TIL-I"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "politecnico_di_torino__mechanical_engineering", universityId = "politecnico_di_torino", universityName = "Politecnico di Torino",
            city = "Torino", region = "Piemonte",
            programName = "Mechanical Engineering", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "TIL-I", admissionRoute = "TIL-I",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("TIL-I"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "roma_la_sapienza__global_humanities", universityId = "roma_la_sapienza", universityName = "Roma La Sapienza",
            city = "Roma", region = "Lazio",
            programName = "Global Humanities", fieldCategory = FieldCategory.HUMANITIES,
            relatedCareers = listOf(CareerPath.OTHER), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E / SAT",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "29.04.2025",
            admissionNotes = "MIN.GPA: 70/100  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E / SAT olarak geçiyordu).",
            extraNotes = "MINIMUM GPA: 70/100",
            tags = listOf("CEnT-S", "SAT (alternatif)"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "roma_la_sapienza__applied_computer_science_and_artificial_intelligence", universityId = "roma_la_sapienza", universityName = "Roma La Sapienza",
            city = "Roma", region = "Lazio",
            programName = "Applied Computer Science and Artificial  Intelligence", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I / SAT",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "29.04.2025",
            admissionNotes = "MIN.GPA: 75/100  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I / SAT olarak geçiyordu).",
            extraNotes = "MINIMUM GPA: 75/100",
            tags = listOf("CEnT-S", "SAT (alternatif)"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "roma_la_sapienza__classics", universityId = "roma_la_sapienza", universityName = "Roma La Sapienza",
            city = "Roma", region = "Lazio",
            programName = "Classics", fieldCategory = FieldCategory.HUMANITIES,
            relatedCareers = listOf(CareerPath.OTHER), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E / SAT",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "29.04.2025",
            admissionNotes = "MINIMUM GPA: 75/100  • English TOLC-E min.  13/36 net  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E / SAT olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S", "SAT (alternatif)"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "roma_la_sapienza__economics_and_finance", universityId = "roma_la_sapienza", universityName = "Roma La Sapienza",
            city = "Roma", region = "Lazio",
            programName = "Economics and Finance", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E / SAT",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "29.04.2025",
            admissionNotes = "MIN. GPA: 75/100 Değerlendirmeye alınabilmek için: TOLC-E min. 13/36 veya daha yüksek puan; SAT min. 960/1600 veya daha yüksek puan.  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E / SAT olarak geçiyordu).",
            extraNotes = "SAT (College Board), 960/1600 veya daha yüksek puan;  • İngilizce TOLC-E (ayrıca TOLC@HOME modunda), 13/36 veya daha yüksek puan.",
            tags = listOf("CEnT-S", "SAT (alternatif)"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "roma_la_sapienza__business_sciences", universityId = "roma_la_sapienza", universityName = "Roma La Sapienza",
            city = "Roma", region = "Lazio",
            programName = "Business Sciences", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E / SAT",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "29.04.2025",
            admissionNotes = "MIN. GPA: 75/100 Değerlendirmeye alınabilmek için: TOLC-E min. 9/36 veya daha yüksek puan; SAT min. 960/1600 veya daha yüksek puan.  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E / SAT olarak geçiyordu).",
            extraNotes = "ASGARİ GPA: 75/100",
            tags = listOf("CEnT-S", "SAT (alternatif)"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "roma_la_sapienza__molecular_biology_medicinal_chemistry_and_computer_science_for", universityId = "roma_la_sapienza", universityName = "Roma La Sapienza",
            city = "Latina", region = "Lazio",
            programName = "Molecular Biology, Medicinal Chemistry  and Computer Science for Pharmaceutical  Applications", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-F / SAT",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "29.04.2025",
            admissionNotes = "MIN.GPA: 60/100 non-eu kontenjan:30  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-F / SAT olarak geçiyordu).",
            extraNotes = "MINIMUM GPA: 60/100 non-eu kontenjan:30",
            tags = listOf("CEnT-S", "SAT (alternatif)"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "roma_la_sapienza_rieti__sustainable_building_engineering", universityId = "roma_la_sapienza_rieti", universityName = "Roma La Sapienza -RIETI",
            city = "Rieti", region = "Lazio",
            programName = "Sustainable Building Engineering", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I / SAT",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "29.04.2025",
            admissionNotes = "MIN.GPA: 80/100  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I / SAT olarak geçiyordu).",
            extraNotes = "GPA min. 80/100",
            tags = listOf("CEnT-S", "SAT (alternatif)"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "roma_tor_vergata__global_governance", universityId = "roma_tor_vergata", universityName = "Roma Tor Vergata",
            city = "Roma", region = "Lazio",
            programName = "Global Governance", fieldCategory = FieldCategory.LAW_INTERNATIONAL,
            relatedCareers = listOf(CareerPath.LAW), primaryStudyArea = ExamType.TOLC_SU,
            admissionExam = "Mülakat", admissionRoute = "Interview",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Aralık 2024",
            admissionNotes = "Denklik-CIMEA. %40 CV-Okul belgeleri % 60 mülakat. Kontenjanı fazla",
            extraNotes = "",
            tags = listOf("Mülakat"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "roma_tor_vergata__business_administration_economics", universityId = "roma_tor_vergata", universityName = "Roma Tor Vergata",
            city = "Roma", region = "Lazio",
            programName = "Business Administration & Economics", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E - Oral Interview",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "non-eu kontenjan: 5  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E - Oral Interview olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "roma_tor_vergata__engineering_sciences", universityId = "roma_tor_vergata", universityName = "Roma Tor Vergata",
            city = "Roma", region = "Lazio",
            programName = "Engineering Sciences", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "Üniversite Sınavı", admissionRoute = "University Exam",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Üniversite Sınavı"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "roma_tor_vergata__pharmacy", universityId = "roma_tor_vergata", universityName = "Roma Tor Vergata",
            city = "Roma", region = "Lazio",
            programName = "Pharmacy", fieldCategory = FieldCategory.SCIENCE_BIOTECH,
            relatedCareers = listOf(CareerPath.BIOLOGY), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Üniversite Sınavı", admissionRoute = "University Exam",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Geçen yıl Nisanda açmış",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Üniversite Sınavı"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "sassari__computer_engineering", universityId = "sassari", universityName = "Sassari",
            city = "Sassari", region = "Sardegna",
            programName = "Computer Engineering", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "Güncel resmi duyuru kontrol edilmeli", admissionRoute = "",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf(), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "siena__economics_and_business", universityId = "siena", universityName = "Siena",
            city = "Siena", region = "Toscana",
            programName = "Economics and Business", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Üniversite Sınavı", admissionRoute = "University Exam / SAT",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "",
            extraNotes = "",
            tags = listOf("Üniversite Sınavı", "SAT (alternatif)"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "torino__economics_and_finance_with_data_science", universityId = "torino", universityName = "Torino",
            city = "Torino", region = "Piemonte",
            programName = "Economics and Finance with Data Science", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "SAT", admissionRoute = "TOLC-E",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Yaklaşık: 2800 (güncel resmi duyuru kontrol edilmeli).", openingDate = "24.02.2025",
            deadlineNote = "30.04.2025",
            admissionNotes = "BU YIL AÇILDI. non-eu kontenjan:45 Dil sertifikası istenmiyor, TOLC-E sınav puanına göre değerlendirilecek denilmiş. TOLC-E Reading bölümünden min. 5 puan alma zorunluluğu var.  Bu program SAT ile kabul eder.",
            extraNotes = "",
            tags = listOf("SAT"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "torino__global_law_and_transnational_legal_studies", universityId = "torino", universityName = "Torino",
            city = "Torino", region = "Piemonte",
            programName = "Global Law and Transnational Legal Studies", fieldCategory = FieldCategory.LAW_INTERNATIONAL,
            relatedCareers = listOf(CareerPath.LAW), primaryStudyArea = ExamType.TOLC_SU,
            admissionExam = "TOLC-SU", admissionRoute = "TOLC-SU",
            languageRequirement = "İngilizce yeterlilik gerekebilir; güncel resmi duyuru kontrol edilmeli.",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "24.02.2025",
            deadlineNote = "30.04.2025",
            admissionNotes = "TOLC-SU sınavının yalnızca İngilizce bölümü değerlendirmeye alınır.",
            extraNotes = "",
            tags = listOf("TOLC-SU"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "torino__business_management", universityId = "torino", universityName = "Torino",
            city = "Torino", region = "Piemonte",
            programName = "Business & Management", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "SAT", admissionRoute = "SAT",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "24.02.2025",
            deadlineNote = "30.04.2025 23.59",
            admissionNotes = "IELTS course is free for all the students enrolled in this degree",
            extraNotes = "",
            tags = listOf("SAT"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "trento__economics_and_management", universityId = "trento", universityName = "Trento",
            city = "Trento", region = "Trentino-Alto Adige",
            programName = "Economics and Management", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E / SAT / GMAT",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "12.03.2025",
            admissionNotes = "BURS VERMİYOR Non-eu kontenjan: 5 Avrupa dışı adaylar için, 1 Ocak 2024 ile 12 Mart 2025 arasında elde edilen en iyi TOLC test sonucu dikkate alınacaktır. TOLC puanı 100'lük bir ölçeğe göre normalleştirilir ve uygunluk için en az 60/100 puan gerekir. İngilizce dil bölümü normalleştirme için kullanılan puandan hariç tutulur. Ön Kayıt: Must be completed by the deadlines indicated in the published rankings. 80 € tutarında iade edilmeyen bir ücret gereklidir.  Eğitim yeterlilik onayı: Unitrento web sitesinde yayınlanan talimatları izleyerek 7 Temmuz ile 18 Temmuz 2025 tarihleri ​​arasında tamamlanmalıdır.  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E / SAT / GMAT olarak geçiyordu).",
            extraNotes = "BURS YOK | 27 Şubat test | NON-EU 10 kontenjan",
            tags = listOf("CEnT-S", "SAT (alternatif)"), isPublic = true, infoUrl = "https://offertaformativa.unitn.it/en/L/economics-and-management"
        ),
        BachelorProgram(
            id = "trento__computer_communications_and_electronic_engineering", universityId = "trento", universityName = "Trento",
            city = "Trento", region = "Trentino-Alto Adige",
            programName = "Computer, Communications and Electronic Engineering", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "12.03.2025",
            admissionNotes = "BURS VERMİYOR.  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I olarak geçiyordu).",
            extraNotes = "BURS YOK",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "trento__computer_sciences", universityId = "trento", universityName = "Trento",
            city = "Trento", region = "Trentino-Alto Adige",
            programName = "Computer Sciences", fieldCategory = FieldCategory.ENGINEERING,
            relatedCareers = listOf(CareerPath.ENGINEERING, CareerPath.COMPUTER_SCIENCE), primaryStudyArea = ExamType.TIL_I,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-I",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvurular açık (dönem doğrulanmalı)",
            deadlineNote = "12.03.2025 / (eu) 09.05.2025 / (eu) 31.07.2025",
            admissionNotes = "BURS VERMİYOR Non-eu kontenjan:25 TOLC-I:min. 18/50 1 Ocak 2024 ile 12 Mart 2025 tarihleri ​​arasında elde edilen en iyi skor dikkate alınacaktır.  Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-I olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "trento__comparative_european_and_international_legal_studies_ceils", universityId = "trento", universityName = "Trento",
            city = "Trento", region = "Trentino-Alto Adige",
            programName = "Comparative, European and International Legal Studies - CEILS", fieldCategory = FieldCategory.LAW_INTERNATIONAL,
            relatedCareers = listOf(CareerPath.LAW), primaryStudyArea = ExamType.TOLC_SU,
            admissionExam = "Üniversite Sınavı", admissionRoute = "University Exam",
            languageRequirement = "IELTS (min. 6.0)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "05.02.2025",
            admissionNotes = "BURS VERMİYOR Entry Test: 27.02.2025 online sınav içeriği aşağıdaki gibidir: UniTrento Admission Test The admission test consists of 60 multiple-choice questions divided as follows: 50 aptitude and general culture questions, divided into: • 30 reading and text comprehension questions • 20 aptitude questions on general culture with an international focus 10 IT skills and logical reasoning questions, divided into: • logical reasoning questions • basic IT questions The duration of the test (60 questions) is 60 minutes. The selection process is conducted entirely in English",
            extraNotes = "BURS YOK TRENTO'DA. Admission Tests: 27.02.2025",
            tags = listOf("Üniversite Sınavı"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "universita_di_pisa__management_for_business_and_economics", universityId = "universita_di_pisa", universityName = "Università di PISA",
            city = "Pisa", region = "Toscana",
            programName = "Management for Business and Economics", fieldCategory = FieldCategory.BUSINESS_ECONOMICS,
            relatedCareers = listOf(CareerPath.ECONOMICS), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "CEnT-S", admissionRoute = "TOLC-E",
            languageRequirement = "IELTS (min. 6.0)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Başvuru dönemi henüz açıklanmadı",
            deadlineNote = "Başvuru tarihleri her yıl değişir; güncel resmi duyuru kontrol edilmeli.",
            admissionNotes = "Kabul yolu CEnT-S kapsamında değerlendirilir (kaynak listede TOLC-E olarak geçiyordu).",
            extraNotes = "",
            tags = listOf("CEnT-S"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "universita_di_pisa__iph_cultural_heritage_studies_art_history_or_classical_archa", universityId = "universita_di_pisa", universityName = "Università di PISA",
            city = "Pisa", region = "Toscana",
            programName = "IPH Cultural Heritage Studies (Art History or Classical Archaeology)", fieldCategory = FieldCategory.HUMANITIES,
            relatedCareers = listOf(CareerPath.OTHER), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Mülakat", admissionRoute = "Interview",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Geçen yıl Mart",
            deadlineNote = "Geçen yıl Temmuz",
            admissionNotes = "*Art History veya Classical Archaeology bölümünü seçebilirsiniz.  *İlk yıl İngilizce, diğer yıllar İtalyanca  *Okul harç ücreti dışında 3200 € ücreti vardır. (Burs alsanız bile bu ücret ödenir)",
            extraNotes = "",
            tags = listOf("Mülakat"), isPublic = true, infoUrl = "https://www.unipi.it/index.php/programmes-held-in-english/item/15061-bachelor-s-degree-in-humanities-iph"
        ),
        BachelorProgram(
            id = "universita_di_pisa__iph_studies_in_performing_arts_and_communication", universityId = "universita_di_pisa", universityName = "Università di PISA",
            city = "Pisa", region = "Toscana",
            programName = "IPH Studies in Performing Arts and Communication", fieldCategory = FieldCategory.COMMUNICATION_MEDIA,
            relatedCareers = listOf(CareerPath.OTHER), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Mülakat", admissionRoute = "Interview",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Geçen yıl Mart",
            deadlineNote = "Geçen yıl Temmuz",
            admissionNotes = "*Performing Arts veya Communication bölümünü seçebilirsiniz.  *İlk yıl İngilizce, diğer yıllar İtalyanca  *Okul harç ücreti dışında 3200 € ücreti vardır. (Burs alsanız bile bu ücret ödenir)",
            extraNotes = "",
            tags = listOf("Mülakat"), isPublic = true, infoUrl = "https://www.unipi.it/index.php/programmes-held-in-english/item/15061-bachelor-s-degree-in-humanities-iph"
        ),
        BachelorProgram(
            id = "universita_di_pisa__iph_philosophy", universityId = "universita_di_pisa", universityName = "Università di PISA",
            city = "Pisa", region = "Toscana",
            programName = "IPH Philosophy", fieldCategory = FieldCategory.HUMANITIES,
            relatedCareers = listOf(CareerPath.OTHER), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Mülakat", admissionRoute = "Interview",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Geçen yıl Mart",
            deadlineNote = "Geçen yıl Temmuz",
            admissionNotes = "*İlk yıl İngilizce, diğer yıllar İtalyanca  *Okul harç ücreti dışında 3200 € ücreti vardır. (Burs alsanız bile bu ücret ödenir)",
            extraNotes = "",
            tags = listOf("Mülakat"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "universita_di_pisa__iph_history", universityId = "universita_di_pisa", universityName = "Università di PISA",
            city = "Pisa", region = "Toscana",
            programName = "IPH History", fieldCategory = FieldCategory.HUMANITIES,
            relatedCareers = listOf(CareerPath.OTHER), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Mülakat", admissionRoute = "Interview",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Geçen yıl Mart",
            deadlineNote = "Geçen yıl Temmuz",
            admissionNotes = "*İlk yıl İngilizce, diğer yıllar İtalyanca  *Okul harç ücreti dışında 3200 € ücreti vardır. (Burs alsanız bile bu ücret ödenir)",
            extraNotes = "",
            tags = listOf("Mülakat"), isPublic = true, infoUrl = ""
        ),
        BachelorProgram(
            id = "universita_di_pisa__iph_european_languages_and_literatures", universityId = "universita_di_pisa", universityName = "Università di PISA",
            city = "Pisa", region = "Toscana",
            programName = "IPH European Languages and Literatures", fieldCategory = FieldCategory.HUMANITIES,
            relatedCareers = listOf(CareerPath.OTHER), primaryStudyArea = ExamType.CENT_S,
            admissionExam = "Mülakat", admissionRoute = "Interview",
            languageRequirement = "IELTS (min. 5.5)",
            tuitionNote = "Ücret bilgisi için güncel resmi duyuru kontrol edilmeli.", openingDate = "Geçen yıl Mart",
            deadlineNote = "Geçen yıl Temmuz",
            admissionNotes = "*İlk yıl İngilizce, diğer yıllar İtalyanca  *Okul harç ücreti dışında 3200 € ücreti vardır. (Burs alsanız bile bu ücret ödenir)",
            extraNotes = "",
            tags = listOf("Mülakat"), isPublic = true, infoUrl = ""
        ),
    )
}

