package com.edumio.app.dailychallenge

import com.edumio.app.core.ExamType
import kotlinx.coroutines.async
import kotlinx.coroutines.awaitAll
import kotlinx.coroutines.runBlocking
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test
import java.util.TimeZone

/**
 * Proves the hard Daily Challenge invariants: exactly ONE immutable challenge per account per day,
 * generated once, never regenerated by reopening, process death, rotation, switching exams, review,
 * or premium; new challenge next day; completed challenges frozen; account isolation; sync restore.
 *
 * Runs the real [DailyChallengeEngine] against an in-memory store (see [InMemoryDailyChallengeDao]),
 * so these are behavioural guarantees, not mocks-of-the-thing-under-test.
 */
class DailyChallengeImmutabilityTest {

    private val utc: TimeZone = TimeZone.getTimeZone("UTC")
    private val t0 = 1_700_000_000_000L          // fixed "now" (a day boundary is irrelevant; UTC-stable)
    private val nextDay = t0 + 26L * 3600 * 1000 // firmly the next UTC calendar day

    private fun imatSetup(): Triple<InMemoryDailyChallengeDao, FakeDcContent, RecordingAnalytics> {
        val dao = InMemoryDailyChallengeDao()
        val content = FakeDcContent.forExam(ExamType.IMAT, perSection = 12)
        return Triple(dao, content, RecordingAnalytics())
    }

    private fun ids(csv: String) = csv.split(",").filter { it.isNotBlank() }

    // ── 1. generated exactly once + IMAT gives 5 new questions ────────────────────────────────────
    @Test
    fun challenge_isGeneratedOnlyOnce() = runBlocking {
        val (dao, content, an) = imatSetup()
        val engine = testEngine(dao, content, an)
        val userId = "u1"

        val first = engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        val second = engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!

        assertEquals(5, first.questions.size)
        assertEquals(first.challenge.challengeId, second.challenge.challengeId)
        assertEquals(first.challenge.questionIdsCsv, second.challenge.questionIdsCsv)
        assertEquals(1, dao.countChallengesForDay(userId, first.challenge.localDate))
        assertEquals(1, dao.countChallengesForUser(userId))
        assertEquals("generated exactly one challenge", 1, an.count(DcEvents.CHALLENGE_GENERATED))
    }

    // ── 2 & 3 & 4. reopen / process death / rotation → SAME questions, no new generation ──────────
    @Test
    fun reopen_processDeath_rotation_returnSameChallenge() = runBlocking {
        val (dao, content, _) = imatSetup()
        val userId = "u1"
        val original = testEngine(dao, content).getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        val originalIds = ids(original.challenge.questionIdsCsv)

        // A brand-new engine instance sharing the SAME store models reopen / process death / rotation
        // (Activity recreated → new engine, persistent DB).
        repeat(3) {
            val freshEngine = testEngine(dao, content, RecordingAnalytics())
            val again = freshEngine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
            assertEquals(originalIds, ids(again.challenge.questionIdsCsv))
        }
        assertEquals(1, dao.countChallengesForUser(userId))
    }

    // ── 5. switching exams returns the SAME challenge (never one-per-exam) ────────────────────────
    @Test
    fun switchingExams_returnsSameChallenge() = runBlocking {
        val (dao, content, an) = imatSetup()
        val engine = testEngine(dao, content, an)
        val userId = "u1"

        val imat = engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        val afterSwitchToCent = engine.getOrCreateToday(userId, ExamType.CENT_S, utc, t0)!!
        val afterSwitchToTil = engine.getOrCreateToday(userId, ExamType.TIL_I, utc, t0)!!

        assertEquals(imat.challenge.questionIdsCsv, afterSwitchToCent.challenge.questionIdsCsv)
        assertEquals(imat.challenge.questionIdsCsv, afterSwitchToTil.challenge.questionIdsCsv)
        // examProfile stays the exam it was generated from — the challenge is not re-authored.
        assertEquals(ExamType.IMAT.name, afterSwitchToCent.challenge.examProfile)
        assertEquals(1, dao.countChallengesForDay(userId, imat.challenge.localDate))
        assertEquals(1, dao.countChallengesForUser(userId))
        assertEquals(1, an.count(DcEvents.CHALLENGE_GENERATED))
    }

    // ── 5b. even switching to an UNSUPPORTED exam still returns the existing challenge ────────────
    @Test
    fun switchingToUnsupportedExam_stillReturnsExisting() = runBlocking {
        val (dao, content, _) = imatSetup()
        val engine = testEngine(dao, content)
        val userId = "u1"

        val imat = engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        assertFalse(DailyChallengeBlueprint.isSupported(ExamType.SAT))
        val afterSwitch = engine.getOrCreateToday(userId, ExamType.SAT, utc, t0)
        assertEquals(imat.challenge.questionIdsCsv, afterSwitch!!.challenge.questionIdsCsv)
    }

    // ── 5c. an unsupported exam with NO existing challenge yields nothing (no crash, no phantom) ──
    @Test
    fun unsupportedExam_withNoChallenge_returnsNull() = runBlocking {
        val (dao, content, _) = imatSetup()
        val engine = testEngine(dao, content)
        assertNull(engine.getOrCreateToday("u1", ExamType.SAT, utc, t0))
        assertEquals(0, dao.countChallengesForUser("u1"))
    }

    // ── 6 & 7. no duplicates under concurrency; exactly one per account per day ───────────────────
    @Test
    fun concurrentOpens_produceExactlyOneChallenge() = runBlocking {
        val (dao, content, an) = imatSetup()
        val engine = testEngine(dao, content, an)
        val userId = "u1"

        val results = (1..24).map {
            async { engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0) }
        }.awaitAll().filterNotNull()

        val distinctCsv = results.map { it.challenge.questionIdsCsv }.toSet()
        assertEquals("all concurrent opens saw the same challenge", 1, distinctCsv.size)
        assertEquals(1, dao.countChallengesForDay(userId, results.first().challenge.localDate))
        assertEquals(1, dao.countChallengesForUser(userId))
        assertEquals("generated exactly once despite 24 concurrent opens", 1, an.count(DcEvents.CHALLENGE_GENERATED))
    }

    // ── 8. next local day creates a brand-new, independent challenge ─────────────────────────────
    @Test
    fun nextDay_createsNewChallenge() = runBlocking {
        val (dao, content, _) = imatSetup()
        val engine = testEngine(dao, content)
        val userId = "u1"

        val d1 = engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        // Questions are consumed when ANSWERED, not when generated, so answer day 1 before rolling over.
        ids(d1.challenge.questionIdsCsv).forEach {
            engine.submitAnswer(userId, d1.challenge.localDate, it, 0, true, 100, t0)
        }
        val d2 = engine.getOrCreateToday(userId, ExamType.IMAT, utc, nextDay)!!

        assertNotEquals("distinct local days", d1.challenge.localDate, d2.challenge.localDate)
        assertNotEquals("distinct question sets", d1.challenge.questionIdsCsv, d2.challenge.questionIdsCsv)
        // no ANSWERED id is ever re-served (retirement happens on answer)
        assertTrue(ids(d1.challenge.questionIdsCsv).intersect(ids(d2.challenge.questionIdsCsv).toSet()).isEmpty())
        assertEquals(1, dao.countChallengesForDay(userId, d1.challenge.localDate))
        assertEquals(1, dao.countChallengesForDay(userId, d2.challenge.localDate))
        assertEquals(2, dao.countChallengesForUser(userId))
    }

    // ── 9. completed challenge cannot regenerate ─────────────────────────────────────────────────
    @Test
    fun completedChallenge_cannotRegenerate() = runBlocking {
        val (dao, content, an) = imatSetup()
        var completedHookCalls = 0
        val engine = testEngine(dao, content, an, onCompleted = { completedHookCalls++ })
        val userId = "u1"

        val gen = engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        val qids = ids(gen.challenge.questionIdsCsv)
        var last = gen
        for ((i, qid) in qids.withIndex()) {
            last = engine.submitAnswer(userId, gen.challenge.localDate, qid, chosenIndex = 0, isCorrect = i < 3, timeMs = 100, nowMs = t0)!!
        }
        assertTrue("completed after 5 answers", last.completed)
        assertEquals(ChallengeStatus.COMPLETED.name, last.challenge.status)
        assertEquals(3, last.challenge.score)
        assertEquals(1, completedHookCalls) // reminder-suppression hook fired exactly once

        // reopening after completion returns the SAME, still-completed challenge — never a 6th question
        val reopened = engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        assertEquals(gen.challenge.questionIdsCsv, reopened.challenge.questionIdsCsv)
        assertTrue(reopened.completed)
        assertEquals(1, dao.countChallengesForUser(userId))
        assertEquals(1, an.count(DcEvents.CHALLENGE_GENERATED))
        assertEquals(1, an.count(DcEvents.CHALLENGE_COMPLETED))
    }

    // ── resume: after N answers, resume cursor is N (survives via persisted answers/currentIndex) ─
    @Test
    fun resumesAtNextUnansweredQuestion() = runBlocking {
        val (dao, content, _) = imatSetup()
        val engine = testEngine(dao, content)
        val userId = "u1"

        val gen = engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        val qids = ids(gen.challenge.questionIdsCsv)
        engine.submitAnswer(userId, gen.challenge.localDate, qids[0], 0, true, 100, t0)
        val afterTwo = engine.submitAnswer(userId, gen.challenge.localDate, qids[1], 0, false, 100, t0)!!

        assertEquals(2, afterTwo.answered)
        assertEquals(2, afterTwo.challenge.currentIndex)
        assertEquals(
            2,
            DailyChallengeHomePresenter.resumeIndex(afterTwo.answered, afterTwo.total, afterTwo.completed),
        )
        // The question order/ids are unchanged by answering.
        assertEquals(gen.challenge.questionIdsCsv, afterTwo.challenge.questionIdsCsv)
    }

    // ── 10. review never generates new questions / never creates a challenge ─────────────────────
    @Test
    fun review_neverGeneratesNewQuestions() = runBlocking {
        val (dao, content, _) = imatSetup()
        val engine = testEngine(dao, content)
        val review = ReviewEngine(dao, content, RecordingAnalytics())
        val userId = "u1"

        val gen = engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        val servedIds = ids(gen.challenge.questionIdsCsv).toSet()
        // get two wrong so the review queue has items
        val qids = servedIds.toList()
        engine.submitAnswer(userId, gen.challenge.localDate, qids[0], 0, false, 100, t0)
        engine.submitAnswer(userId, gen.challenge.localDate, qids[1], 0, false, 100, t0)

        val seenBefore = dao.getSeenQuestionIds(userId, ExamType.IMAT.name).toSet()
        val challengesBefore = dao.countChallengesForUser(userId)

        val queue = review.getReviewQueue(userId, ExamType.IMAT, isPremium = true, nowMs = t0 + 1000)

        // review only ever surfaces already-served questions
        assertTrue(queue.all { it.question.id in servedIds })
        // and it introduces no new seen questions and no new challenge
        assertEquals(seenBefore, dao.getSeenQuestionIds(userId, ExamType.IMAT.name).toSet())
        assertEquals(challengesBefore, dao.countChallengesForUser(userId))
        // Consumption is answer-driven: exactly the two answered questions are recorded, not all five.
        assertEquals(2, dao.getSeenQuestionIds(userId, ExamType.IMAT.name).size)
    }

    // ── 11. reinstall restores today's challenge after sync (fresh store + snapshot) ─────────────
    @Test
    fun reinstall_restoresChallengeAfterSync() = runBlocking {
        // Install #1: generate + answer two.
        val dao1 = InMemoryDailyChallengeDao()
        val content = FakeDcContent.forExam(ExamType.IMAT, perSection = 12)
        val engine1 = testEngine(dao1, content)
        val userId = "u1"
        val gen = engine1.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        val qids = ids(gen.challenge.questionIdsCsv)
        engine1.submitAnswer(userId, gen.challenge.localDate, qids[0], 0, true, 100, t0)
        engine1.submitAnswer(userId, gen.challenge.localDate, qids[1], 0, false, 100, t0)

        // Sync: serialize the WHOLE account snapshot (challenge + answers + retirement/review/streak).
        val wire = DailyChallengeSyncCodec.toJson(engine1.exportSnapshot(userId))

        // Install #2 (reinstall): brand-new empty store, then restore the pulled snapshot.
        val dao2 = InMemoryDailyChallengeDao()
        val an2 = RecordingAnalytics()
        val engine2 = testEngine(dao2, content, an2)
        engine2.restoreSnapshot(DailyChallengeSyncCodec.fromJson(wire)!!)

        // Opening on the fresh install returns the SAME challenge & progress, and generates nothing new.
        val restored = engine2.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        assertEquals(gen.challenge.questionIdsCsv, restored.challenge.questionIdsCsv)
        assertEquals(2, restored.answered)
        assertEquals(1, dao2.countChallengesForUser(userId))
        assertEquals("no regeneration after restore", 0, an2.count(DcEvents.CHALLENGE_GENERATED))

        // Retirement survives the reinstall: the NEXT day must NOT re-serve any of day D's questions.
        val nextDayChallenge = engine2.getOrCreateToday(userId, ExamType.IMAT, utc, nextDay)!!
        assertTrue(
            "reinstalled account must not re-serve already-retired questions",
            ids(nextDayChallenge.challenge.questionIdsCsv).intersect(qids.toSet()).isEmpty(),
        )
    }

    // ── undersupply: when the unseen pool cannot fill all 5 slots, serve NOTHING (never a stuck partial) ─
    @Test
    fun undersizedPool_servesNoChallenge() = runBlocking {
        val dao = InMemoryDailyChallengeDao()
        val content = FakeDcContent.forExam(ExamType.IMAT, perSection = 12)
        val engine = testEngine(dao, content)
        val userId = "u1"
        // Pre-retire all but 3 questions so only 3 unseen remain → a 5-question challenge is impossible.
        val allIds = DailyChallengeBlueprint.sections(ExamType.IMAT).flatMap { s -> (0 until 12).map { "IMAT-$s-$it" } }
        allIds.drop(3).forEach { id ->
            dao.upsertState(UserQuestionStateEntity(userId, id, "IMAT", "biology", "t-$id", QuestionLearnState.SEEN_ONCE.name, timesSeen = 1))
        }
        val result = engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)
        assertNull("must not serve a <5 partial challenge", result)
        assertEquals(0, dao.countChallengesForUser(userId))
    }

    // ── sign-in mid-day: anonymous state is adopted, NOT regenerated into a second challenge ─────────
    @Test
    fun signInMidDay_adoptsAnonChallenge_doesNotRegenerate() = runBlocking {
        val (dao, content, an) = imatSetup()
        val engine = testEngine(dao, content, an)
        val anonId = "anon_abc"
        val accountId = "acct_alice@example.com"

        // Anonymous: generate + answer two.
        val anon = engine.getOrCreateToday(anonId, ExamType.IMAT, utc, t0)!!
        val qids = ids(anon.challenge.questionIdsCsv)
        engine.submitAnswer(anonId, anon.challenge.localDate, qids[0], 0, true, 100, t0)
        engine.submitAnswer(anonId, anon.challenge.localDate, qids[1], 0, false, 100, t0)

        // Sign in for the first time → link anon state to the account.
        val migrated = engine.migrateAccount(anonId, accountId)
        assertTrue(migrated)

        // Reopening Home as the signed-in account returns the SAME challenge & progress — NO second one.
        val afterSignIn = engine.getOrCreateToday(accountId, ExamType.IMAT, utc, t0)!!
        assertEquals(anon.challenge.questionIdsCsv, afterSignIn.challenge.questionIdsCsv)
        assertEquals(2, afterSignIn.answered)
        assertEquals("exactly one challenge for the account that day", 1, dao.countChallengesForDay(accountId, anon.challenge.localDate))
        assertEquals("account generated no NEW challenge on sign-in", 1, an.count(DcEvents.CHALLENGE_GENERATED))
        // migration is idempotent: a repeat adopts nothing new
        assertFalse(engine.migrateAccount(anonId, accountId))
    }

    // ── returning account (has prior history) that used an anon session today: adopt, don't regenerate ─
    @Test
    fun returningAccount_signInAfterAnonSameDay_adoptsNotRegenerates() = runBlocking {
        val (dao, content, an) = imatSetup()
        val engine = testEngine(dao, content, an)
        val accountId = "acct_bob"
        val anonId = "anon_z"

        // Account has PRIOR-day history (day N-1), completed → it also owns a streak.
        val prev = engine.getOrCreateToday(accountId, ExamType.IMAT, utc, t0)!!
        ids(prev.challenge.questionIdsCsv).forEach { qid ->
            engine.submitAnswer(accountId, prev.challenge.localDate, qid, 0, true, 100, t0)
        }
        // Signed OUT on day N: anonymous session does today's challenge, answers one.
        val anon = engine.getOrCreateToday(anonId, ExamType.IMAT, utc, nextDay)!!
        engine.submitAnswer(anonId, anon.challenge.localDate, ids(anon.challenge.questionIdsCsv)[0], 0, false, 100, nextDay)

        // Signs back into the SAME account (which has history) → adopt today's anon challenge.
        assertTrue(engine.migrateAccount(anonId, accountId))

        val genBefore = an.count(DcEvents.CHALLENGE_GENERATED)
        val today = engine.getOrCreateToday(accountId, ExamType.IMAT, utc, nextDay)!!
        assertEquals("adopted the anon challenge, did not regenerate", anon.challenge.questionIdsCsv, today.challenge.questionIdsCsv)
        assertEquals(1, today.answered)
        assertEquals("no fresh generation for the returning account", genBefore, an.count(DcEvents.CHALLENGE_GENERATED))
        // exactly one challenge per day; the account keeps its prior-day history
        assertEquals(1, dao.countChallengesForDay(accountId, prev.challenge.localDate))
        assertEquals(1, dao.countChallengesForDay(accountId, anon.challenge.localDate))
        assertEquals(2, dao.countChallengesForUser(accountId))
    }

    // ── migration is self-healing: a crash after only the challenge is copied is repaired on retry ───
    @Test
    fun migration_isIdempotentAndSelfHealing() = runBlocking {
        val (dao, content, _) = imatSetup()
        val engine = testEngine(dao, content)
        val anonId = "anon_p"; val accountId = "acct_q"
        val anon = engine.getOrCreateToday(anonId, ExamType.IMAT, utc, t0)!!
        engine.submitAnswer(anonId, anon.challenge.localDate, ids(anon.challenge.questionIdsCsv)[0], 0, false, 100, t0)

        // Simulate a crash mid-migration under the (challenge-written-LAST) restore order: the retirement
        // states landed but the challenge row did not, so the day is NOT yet "owned".
        dao.getAllStatesForUser(anonId).forEach { dao.upsertState(it.copy(userId = accountId)) }
        assertEquals(0, dao.countChallengesForUser(accountId))

        // Re-run migration → re-adopts the whole day (challenge + answer) and does not double-write states.
        engine.migrateAccount(anonId, accountId)
        assertEquals(1, dao.countChallengesForDay(accountId, anon.challenge.localDate))
        assertEquals(anon.challenge.questionIdsCsv, dao.getChallengeForDay(accountId, anon.challenge.localDate)!!.questionIdsCsv)
        // One question was answered, so exactly one learning state exists — and migrating twice must
        // not duplicate it (consumption is answer-driven, so five states would be wrong here).
        assertEquals("retirement states not double-counted", 1, dao.getAllStatesForUser(accountId).size)
        assertEquals(1, dao.countAnswers("$accountId:${anon.challenge.localDate}"))
    }

    // ── review is scoped to the CHALLENGE's exam, not the active one (backs the UI scoping fix) ──────
    @Test
    fun reviewCount_isScopedToChallengeExam() = runBlocking {
        val (dao, content, _) = imatSetup()
        val engine = testEngine(dao, content)
        val userId = "u1"
        val gen = engine.getOrCreateToday(userId, ExamType.IMAT, utc, t0)!!
        engine.submitAnswer(userId, gen.challenge.localDate, ids(gen.challenge.questionIdsCsv)[0], 0, false, 100, t0)

        // wrong answer is reviewable under the challenge's exam (IMAT) and NOT under a different exam.
        assertTrue(engine.reviewCount(userId, ExamType.IMAT, listOf(ReviewQueue.INCORRECT)) >= 1)
        assertEquals(0, engine.reviewCount(userId, ExamType.CENT_S, listOf(ReviewQueue.INCORRECT)))
    }

    // ── 12. a different account (different email → different userId) is fully independent ─────────
    @Test
    fun differentAccount_isIndependentAndStartsFromZero() = runBlocking {
        val (dao, content, _) = imatSetup()
        val engine = testEngine(dao, content)

        val a = engine.getOrCreateToday("alice@example.com-uid", ExamType.IMAT, utc, t0)!!
        val b = engine.getOrCreateToday("bob@example.com-uid", ExamType.IMAT, utc, t0)!!

        // each account has exactly one challenge for the day, independent of the other
        assertEquals(1, dao.countChallengesForUser("alice@example.com-uid"))
        assertEquals(1, dao.countChallengesForUser("bob@example.com-uid"))
        // answering as alice does not touch bob's challenge/progress
        engine.submitAnswer("alice@example.com-uid", a.challenge.localDate, ids(a.challenge.questionIdsCsv)[0], 0, true, 100, t0)
        val bobReopened = engine.getOrCreateToday("bob@example.com-uid", ExamType.IMAT, utc, t0)!!
        assertEquals(0, bobReopened.answered)
        assertEquals(b.challenge.questionIdsCsv, bobReopened.challenge.questionIdsCsv)
    }

    // ── premium never changes the new-question count ─────────────────────────────────────────────
    @Test
    fun premium_neverChangesQuestionCount() = runBlocking {
        val (dao, content, _) = imatSetup()
        val engine = testEngine(dao, content)
        val free = engine.getOrCreateToday("free", ExamType.IMAT, utc, t0, isPremium = false)!!
        val premium = engine.getOrCreateToday("prem", ExamType.IMAT, utc, t0, isPremium = true)!!
        assertEquals(5, free.questions.size)
        assertEquals(5, premium.questions.size)
    }
}
